# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Front End Dev | Notes
email: sam19920516@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, I am Hsinfu. I am learning front end develpment now. And this is a website of my notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sam19920516.github.io/" # the base hostname & protocol for your site
twitter_username: hsinfuyeh
github_username:  hsinfuyeh

# Build settings
markdown: kramdown
